---
- name: "Run OpenVPN as gateway"
  hosts: all
  become: true

  tasks:
  - name: Install OpenVPN
    package:
      update_cache: true
      name: openvpn
      state: present

  - name: Enable OpenVPN service
    service:
      name: openvpn
      state: started
      enabled: true

  - name: Copiar archivo de configuracion
    copy:
      src: ./client.conf
      dest: /etc/openvpn/client.conf
    notify:
      - Restart OpenVPN
  
  - name: Activar IPv4 routing
    lineinfile:
      path: /etc/sysctl.conf
      regexp: '^net.ipv4.ip_forward'
      line: 'net.ipv4.ip_forward = 1'

  - name: Install IPtables-persistent
    package:
      name: iptables-persistent
      state: present

  - name: Enable IPtables-persistent
    service:
      name: netfilter-persistent
      state: started
      enabled: true

  - name: Reglas IPtables
    copy:
      src: ./rules.v4
      dest: /etc/iptables/rules.v4
    notify:
      - Reboot computer

  handlers:
    - name: Restart OpenVPN
      service:
        name: openvpn
        state: restarted
    - name: Reboot computer
      reboot: